import type { Metadata } from 'next'
import './globals.css'
import { Onest } from 'next/font/google'

const onest = Onest({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "CashTrackr",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={onest.className}>
        {children}
      </body>
    </html>
  );
}
